version: "3.8"
services:
  userservice:
    build: ./userservice/demo
    ports:
      - "8081:8081"
    depends_on:
      - userdb
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    networks:
      - users-network

  salaservice:
    build: ./salaservice/demo
    ports:
      - "8082:8082"
    depends_on:
      - saladb
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://saladb:5432/salasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    networks:
      - salas-network

  reservaservice:
    build: ./reservaservice/demo
    ports:
      - "8083:8083"
    depends_on:
      - reservadb
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservadb:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    networks:
      - reservas-network

  userdb:
    image: postgres:15
    container_name: userdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - users-network
    volumes:
      - userdb-data:/var/lib/postgresql/data

  saladb:
    image: postgres:15
    container_name: saladb
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: salasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - salas-network
    volumes:
      - saladb-data:/var/lib/postgresql/data

  reservadb:
    image: postgres:15
    container_name: reservadb
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reservas-network
    volumes:
      - reservadb-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - users-network
      - salas-network
      - reservas-network

  gateway:
    build: ./gateway/demo
    ports:
      - "8080:8080"
    depends_on:
      - userservice
      - salaservice
      - reservaservice
    restart: unless-stopped
    networks:
      - users-network
      - salas-network
      - reservas-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - reservas-network
      - users-network
      - salas-network

networks:
  reservas-network:
  salas-network:
  users-network:

volumes:
  userdb-data:
  saladb-data:
  reservadb-data:
  rabbitmq-data: