version: "3.8"
services:
  userservice:
    build: ./userservice/demo
    ports:
      - "8081:8081"
    depends_on:
      - userdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - reservas-network

  salaservice:
    build: ./salaservice/demo
    ports:
      - "8082:8082"
    depends_on:
      - saladb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://saladb:5432/salasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - reservas-network

  reservaservice:
    build: ./reservaservice/demo
    ports:
      - "8083:8083"
    depends_on:
      - reservadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservadb:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - reservas-network

  userdb:
    image: postgres:15
    container_name: userdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reservas-network
    volumes:
      - userdb-data:/var/lib/postgresql/data

  saladb:
    image: postgres:15
    container_name: saladb
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: salasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reservas-network
    volumes:
      - saladb-data:/var/lib/postgresql/data

  reservadb:
    image: postgres:15
    container_name: reservadb
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reservas-network
    volumes:
      - reservadb-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - reservas-network

networks:
  reservas-network:

volumes:
  userdb-data:
  saladb-data:
  reservadb-data:
